version: "3.7"
services:
    # Base de datos para la persistencia de Kong.
    postgres:
        image: postgres:9.6
        container_name: postgres
        environment:
            - "POSTGRES_USER=root"
            - "POSTGRES_PASSWORD=ficticio"
            - "POSTGRES_DB=kong"
            - "PGDATA=/var/lib/postgresql/data"
        restart: on-failure
        volumes:
            - kong-db:/var/lib/postgresql/data
        networks:
            - kong-net
    # Migracion de las tablas de Kong.
    kong-migrations:
        image: kong:latest
        container_name: kong-migration
        entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
        environment:
            - "KONG_DATABASE=postgres"
            - "KONG_PG_HOST=postgres"
            - "KONG_PG_DATABASE=kong"
            - "KONG_PG_USER=root"
            - "KONG_PG_PASSWORD=ficticio"
        restart: on-failure
        depends_on:
            - postgres
        networks:
            - kong-net
    # Kong.
    kong:
        image: kong:latest
        container_name: kong
        environment:
            - "KONG_DATABASE=postgres"
            - "KONG_PG_HOST=postgres"
            - "KONG_PG_DATABASE=kong"
            - "KONG_PG_USER=root"
            - "KONG_PG_PASSWORD=ficticio"
            - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
            - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
            - "KONG_PROXY_ERROR_LOG=/dev/stderr"
            - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
            #KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
        restart: on-failure
        ports:
            - 8000:8000 # HTTP
            - 8443:8443 # SSL
            - 8001:8001
            #- $KONG_PROXY_ADMIN_API_PORT:8001
            #- $KONG_PROXY_ADMIN_SSL_API_PORT:8444
        depends_on:
            - kong-migrations
        networks:
            - kong-net
    # Konga.
    konga:
        image: pantsel/konga
        container_name: konga
        environment:
            - "TOKEN_SECRET=ficticio"
            - "NODE_ENV=production"
        restart: on-failure
        ports:
            - 1337:1337
        depends_on:
            - postgres
        networks:
            - kong-net
volumes:
    kong-db:
        external: true
networks:
    kong-net:
        external:
            name: red-kong